import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
// import "./components/style.css";
import "./global_mobile_style.css";

import Link from "next/link";
import BootstrapInit from "./(components)/BootstrapInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Shehroz Alam Fitness And Nutrition Coach",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: "Shehroz Alam | Fitness Coach & Transformation Expert",
  description:
    "Join Shehroz Alam, your ultimate fitness guide, to transform your body and mindset. Get personalized workout plans, diet charts, and coaching for real results.",
  keywords: [
    "Shehroz Alam",
    "Fitness Coach",
    "Online Training",
    "Body Transformation",
    "Workout Plans",
    "Nutrition Coaching",
    "Fat Loss",
    "Muscle Building",
  ],
  openGraph: {
    title: "Shehroz Alam | Online Fitness Coaching",
    description:
      "Take the first step towards your transformation with Shehroz Alam. Coaching, meal plans, video guidance, and accountability — all in one place.",
    url: "https://shehroz-alam.vercel.app/",
    siteName: "Shehroz Alam",
    images: [
      {
        url: "https://shehroz-alam.vercel.app/img_1.jpg",
        width: 1200,
        height: 630,
        alt: "Shehroz Alam Fitness Coaching",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapInit />
        {children}
        <div className="adminActions">
          <input type="checkbox" name="adminToggle" className="adminToggle" />
          <a className="adminButton" href="#!">
            <i className="bi bi-person-fill-gear"></i>
          </a>
          <div className="adminButtons">
            <Link href="https://wa.me/+919910772367">
              <i className="bi bi-whatsapp"></i>
            </Link>
            <Link href="https://www.instagram.com/theshehrozalam">
              <i className="bi bi-instagram"></i>
            </Link>
            <Link href="tel:919910772367">
              <i className="bi bi-telephone-fill"></i>
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
